### ISSUE TITLE
Windows Phone 8.1 Support

### ISSUE THREAD

**Issue by AndrewAtAvenza** [AttackPattern/CSharpAnalytics#28]
I've just start using your library -- it's working great! -- but we needed a Windows Phone 8.1 (non-Silverlight) version. I've actually already done the work; do you want me to to push the results back somehow? If so, I'd just need some instruction on how to merge my changes in so I don't clobber the Sliverlight code. I can add the 8.1 project easily enough (renamed as WindowsPhone81) but I had to touch a scattering of code and I'm not sure how to best make that work side-by-side with Silverlight. Use #if & the SILVERLIGHT define?

I've never actually contributed to an existing github project, so I apologize in advance -- I'm not sure what the protocol or procedure is.

Thanks!

**Comment by damieng** [comment]
Hi Andrew.

The first thing will be to branch our repository on GitHub and then push your code up to that.  From there you can issue a pull request and that will give us a reviewable changeset between your repository and ours.

We can then review it and take it from there.  Thanks for contributing!
