### ISSUE TITLE
Prior requests cause null exception in BaseAutoMeasurement::Request

### ISSUE THREAD

**Issue by AndrewAtAvenza** [AttackPattern/CSharpAnalytics#30]
I was fiddling with our app's ability to handle network availability and I started getting null reference exceptions in BaseAutoMeasurement::Request(). It was complaining on the first line:

if (sessionManager.VisitorStatus != VisitorStatus.Active)

because sessionManager was still null. I looked into it and I think the problem is in BaseAutoMeasurement::Start(). Currently, it looks like this:

                await StartRequesterAsync();

                var sessionState = await Load<SessionState>(SessionStorageName);
                sessionManager = new SessionManager(sessionState, configuration.SampleRate);
                if (delayedOptOut != null) SetOptOut(delayedOptOut.Value);

But if I change it to:

                var sessionState = await Load<SessionState>(SessionStorageName);
                sessionManager = new SessionManager(sessionState, configuration.SampleRate);
                await StartRequesterAsync();
                if (delayedOptOut != null) SetOptOut(delayedOptOut.Value);

it stops throwing exceptions. I'm guessing because when the Requester is fired up, it immediately checks for prior requests, queues them, and starts processing them. Unfortunately, sessionManager is initialized later, so its not there, and it fails the Request() call.

So simply creating the SessionManager first solves the problem, but maybe there's a good reason it was created in the order its currently created!

**Comment by damieng** [comment]
Thanks for spotting this problem, I've checked in a fix as 271a94399af71a9997da558c357e939819673504
