### ISSUE TITLE
TrackEvent exchange parameters action and category

### ISSUE THREAD

**Issue by xmedeko** [AttackPattern/CSharpAnalytics#37]
`AutoMeasurement.Client.TrackEvent` has parameters `TrackEvent(string action, string category, ...`. But the Google Analytics shows the category first, then the action. More convenient would be to exchaneg these parameters `TrackEvent(string category, string action, ...`

**Comment by damieng** [comment]
This would be a silently breaking change for all existing users. Would never do that.
